apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: event
  name: event
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: event
    spec:
      containers:
      - image: srijashenkeshi5/event:10
        name: event
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: event
  name: event
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: event
  type: ClusterIP
status:
  loadBalancer: {}
