name: build and push docker image to container registry

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  ci:

    permissions:
      packages: write

    name: "🛠️"
    uses: srija-shenkeshi/workflows/.github/workflows/build-gradle.yml@main
    with:
      REGISTRY: docker.io
      USERNAME: srijashenkeshi5
    secrets:
      REGISTRY_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      
  cd:

    name: deploy
    uses: srija-shenkeshi/workflows/.github/workflows/deploy-gke.yml@main
      with:
        creds: ${{ secrets.GCP_CREDENTIALS }}
      
  

