name: build and push docker image to container registry

on:
  push:
    branches: [main]

  workflow_dispatch:

env:
  REGISTRY: docker.io
  USERNAME: srijashenkeshi5
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  DOCKER_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  ci:

    permissions:
      packages: write

    name: "🛠️"
    uses: srija-shenkeshi/workflows/.github/workflows/build-gradle.yml@main
    with:
      REGISTRY: ${{ env.REGISTRY }}
      USERNAME: ${{ env.USERNAME }}
    secrets:
      REGISTRY_TOKEN: ${{ env.DOCKER_TOKEN}}


